### ISSUE TITLE
dns spoof not working

### ISSUE THREAD

**Issue by darkworks** [xtr4nge/FruityWifi#165]
i installed latest version of fruitywifi on linux-kali 2.0  
i have enabled dns spoof module but its not working
screenshot  of dns spoof 
https://nimbus.everhelper.me/client/notes/share/314562/tHDrb9FApzzFTmoy6fydqruF30fhKW7O/
screehshot of my settings
https://nimbus.everhelper.me/client/notes/share/314564/3A0IRnpIagElPI3FZPbMecNbSqzXS3bi/

**Comment by xtr4nge** [comment]
Hi darkworks,
DNSspoof module is just a GUI for dnsspoof command. 

I can see a few problems in your setup. You are not using the `IN` interface (so I guess that you are not using FruityWiFi as an `[AP]`), but the problem is that there is not interface assigned as `ACTION [sniff|inject]`

For more details please go to the forum as this is a setup issue:
http://fruitywifi.boards.net/

regards,
