### ISSUE TITLE
dhcp isn't working

### ISSUE THREAD

**Issue by A-rotten-Orange** [xtr4nge/FruityWifi#19]
Hi
I am having problems with the dhcp on fruity wifi.
when I start wireless and I try and connect to it via a laptop or my phone dhcp always times out but if i set it to a static address on my laptop or phone it works fine.

**Comment by Rworld-Ravi** [comment]
Hi, 
  I have a netis wifi adapter having RTL8188CUS chipset which supports AP mode with a patched hostapd. I have made a raspberry pi web server using patched-hostapd and dhcp . And as been stated in FruityWifi v2.0 , that it supports realtek chipsets, then which realtek chipset in perticular, because its not working with RTL8188CUS chipset.
  Please reply.
Regards 
Ravi

**Comment by xtr4nge** [comment]
Hi Rworld-Ravi,
FruityWifi uses a combination of Hostapd (3 diff versions that not support Realtek) and Dnsmasq.
You can use [AP] mode Airmon-ng with Realtek chipsets and others not supported by Hostapd. 

For the moment, I'm not planning to include a patched version of Hostapd to support Realtek.

regards,
xtr4nge

**Comment by Rworld-Ravi** [comment]
Thanks for reply,
     Then please suggest some ( as i'll have to look around for
availability ) wifi adapter for  RPi-2 which will work best with
Fruitywifi.????

Regards,
Ravi Verma
