### ISSUE TITLE
Perform OUI lookup when display mac address?

### ISSUE THREAD

**Issue by JackWindows** [xtr4nge/FruityWifi#51]
Can we display the corresponding OUI of a mac address on the status page? I have already made such implementation, the oui information is parsed from a list maintained by wireshark. If you like, I can send a pull request.

**Comment by xtr4nge** [comment]
Hi JackWindows,
For some reason I missed this message. Sorry about that.

We can use macchanger to check the vendor, for example:
`macchanger -l | grep 00:0c:29`

You can also create a module instead of add all the info in the status page, with your current implementation (wireshark). I will publish documentation to create modules very soon.

regards,
xtr4nge
